# Generated by Django 6.0.6 on 2026-06-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('structural', 'Structural & Architectural Designs'), ('construction', 'Building Construction (Residential)'), ('commercial', 'Building Construction (Commercial)'), ('management', 'Site / Project Management'), ('boq', 'BOQ Estimation & Quantity Surveying'), ('decoration', 'Wall Decoration (Screening & Painting)'), ('interior', 'Interior & Exterior Designs'), ('equipment', 'Construction Equipment Rentals'), ('other', 'Other / Not Sure')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('budget', models.CharField(blank=True, choices=[('Below ₦1 Million', 'Below ₦1 Million'), ('₦1M – ₦5M', '₦1M – ₦5M'), ('₦5M – ₦20M', '₦5M – ₦20M'), ('₦20M – ₦100M', '₦20M – ₦100M'), ('Above ₦100M', 'Above ₦100M'), ('Not Yet Determined', 'Not Yet Determined')], max_length=50, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
