# Generated by Django 5.2.8 on 2026-06-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('residential', 'Residential Construction'), ('commercial', 'Commercial Construction'), ('structural', 'Structural Design'), ('interior', 'Interior / Exterior Design'), ('renovation', 'Renovation / Finishing'), ('management', 'Project Management'), ('other', 'Other')], default='other', max_length=50)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_location', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.project')),
            ],
        ),
    ]
