# Generated by Django 5.2.8 on 2026-06-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenge_1_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenge_1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='floors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True, help_text='Add one scope item per line', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_1_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution_1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('planned', 'Planned')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, help_text='Add one tag per line', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, help_text='Add one technology/material/tool per line', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
