# Generated by Django 5.2.8 on 2026-06-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_challenge_1_desc_project_challenge_1_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.project'),
        ),
    ]
