# Generated by Django 5.2.8 on 2026-06-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projectimage_project_projectcomment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectlike',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectcomment',
            name='parent',
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='projectlike',
            name='ip_address',
            field=models.GenericIPAddressField(default=''),
            preserve_default=False,
        ),
    ]
